name: on-push-publish-to-npm
on:
  push:
    branches:
      - master # Change this if not your default branch
    paths:
      - 'packages/aio-metrics-client/package.json'
jobs:
  publish:
    if: github.repository_owner == 'adobe'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm test
      - uses: JS-DevTools/npm-publish@v1
        with:
          dry-run: true
          package: packages/aio-metrics-client/package.json
          token: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
          access: 'public'
